version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - npm install --legacy-peer-deps
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - cp appspec.yml build/
      - cp -r scripts build/

artifacts:
  base-directory: build
  files:
    - '**/*'
    - appspec.yml
    - scripts/**/*
  discard-paths: no