version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install -g npm@latest
  pre_build:
    commands:
      - npm install react-scripts --save
      - npm install --legacy-peer-deps
  build:
    commands:
      - echo "Building React app..."
      - node node_modules/react-scripts/bin/react-scripts.js build
      
artifacts:
  base-directory: build
  files:
    - '**/*'